### PR TITLE
Wrong binary encoding in the AssetCode12 module

### LINKED ISSUE #197: Wrong binary encoding in the `AssetCode12` module
### Precheck

- [ ] Do a quick search and make sure the bug has not been reported yet.
- [ ] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ ] Finally, be nice and have fun!.

### Description

There is a bug in the `StellarBase.XDR.AssetCode12` module in the encoding of the structure, the function is throwing a wrong binary.

If the `code` passed to the structure has a length of less than 12 the encoding should add the remaining bytes of `<<0>>` at the end of the resultant binary, but it is not happening for the `codes` with a length between 5 and 8, this is related to the behaviour of the `XDR.FixedOpaque` module from the `elixir_xdr` library.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.14.0 (compiled with Erlang/OTP 23)`
* Operating system: `Linux Mint 21 Vanessa`

### Current behavior

image

### Expected behavior

image

### Additional context

> You can review the fixFIxedOpaque from the elixir_xdr library for more information: https://github.com/kommitters/elixir_xdr/blob/main/lib/xdr/fixed_opaque.ex

### PR DESCRIPTION
**Pull request by CristhianRodriguezMolina**
Fixes #197

### CODE REVIEW

File: lib/xdr/ledger_entries/asset_code12.ex [hunk 1]
```diff
@@ -45,22 +45,24 @@ defmodule StellarBase.XDR.AssetCode12 do
   @impl true
   def decode_xdr!(bytes, term \\ nil)
 
-  def decode_xdr!(bytes, _term) do
-    {%XDR.FixedOpaque{opaque: code}, rest} =
+  def decode_xdr!(<<bytes::binary-size(12), rest::binary>>, _term) do
```
Comment (miguelnietoa) [inline lib/xdr/ledger_entries/asset_code12.ex:48]: @CristhianRodriguezMolina why is 12-byte pattern matching necessary here?

File: lib/xdr/ledger_entries/asset_code12.ex [hunk 2]
```diff
@@ -45,22 +45,24 @@ defmodule StellarBase.XDR.AssetCode12 do
...
 
     {new(code), rest}
   end
 
+  @spec build_opaque(code :: binary(), length :: non_neg_integer()) :: XDR.FixedOpaque.t()
+  defp build_opaque(code, length) do
+    zeros = 12 - byte_size(code)
+    bin = <<code::binary, 0::zeros*8>>
+    XDR.FixedOpaque.new(bin, length + zeros)
+  end
```
Comment (miguelnietoa) [inline lib/xdr/ledger_entries/asset_code12.ex:60]: @CristhianRodriguezMolina IMHO I have these suggestions about this function:
- I think we could replace `12` with the `@max_length` constant.
- Why don't we use `length` instead of calling the `byte_size/1` function?
- Since this function will pad the `code` until 12 bytes, what about replacing `length + zeros` with `@max_length`, couldn't we?

**Review by miguelnietoa — CHANGES_REQUESTED** [review]
@CristhianRodriguezMolina great fix, some comments added!

File: lib/xdr/ledger_entries/asset_code12.ex (hunk 1 above)
Comment (CristhianRodriguezMolina) [reply lib/xdr/ledger_entries/asset_code12.ex:48]: @miguelnietoa This is in order to get the 12 bytes of the asset_code_12 when decoding the binary of an asset, this is to ensure that all the 12 bytes are off the rest of the binary and avoid errors when continuing with the rest of the decoding.

File: lib/xdr/ledger_entries/asset_code12.ex (hunk 2 above)
Comment (CristhianRodriguezMolina) [reply lib/xdr/ledger_entries/asset_code12.ex:60]: Ok, these changes sound good to me.

**Review by miguelnietoa — APPROVED** [review]
Looks good to me! 👌🏻

**Review by einerzg — APPROVED** [review]
👍🏽
